//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UITextView;

@interface a2qrtgWXxyXpCkyloC : UIViewController
{
    UITextView *_w2Trm8j8WA1h;
}

@property(retain, nonatomic) UITextView *w2Trm8j8WA1h; // @synthesize w2Trm8j8WA1h=_w2Trm8j8WA1h;
- (void).cxx_destruct;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)u4PO:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

