//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

struct f41e9c63f54b {
    char n29OBV28[16];
    CDUnknownFunctionPointerType f3052ffaac9a;
    int f4b4b9bb956b;
    int f05e1640248b;
    double *f404f6cd51b8;
    int dca62b43d1c8;
    int c0PpdmM4;
    int a08b5ace5fa1;
    int f03814e9b960;
    int a5a28bb83dc9;
};

