//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class LMGaugeView, NSDateFormatter, NSLayoutConstraint, NSTimer, NetworkClock, UIButton, UIColor, UILabel, UINavigationController, UIView, UIVisualEffectView, o60HgQoJPY;

@interface j4Phqs6xzCRf6r8DOC : UIViewController
{
    char *f5KmM9n;
    int d9jlugb;
    o60HgQoJPY *o6lRNTp7TK;
    double r3Ze5QkCd;
    long long g89d1oHyGC;
    struct f41e9c63f54b encoder;
    long long u8;
    NSDateFormatter *g0Cjx3fs9fev4;
    NSDateFormatter *g8KnH4tLmtcq2;
    int h6rHlGy0C4gH;
    NetworkClock *f5;
    UIColor *a05cdoFai2RljAP16;
    long long k6K44HnBAB;
    int l6zfb3PkVsxiz;
    struct f41e9c63f54b r0eIaJJX[5];
    int h145ynWYinK8oQd;
    int r35lwzPl;
    int l6R0rKctm;
    NSTimer *a9g8MDch;
    UIButton *_v1n37B8BU8u;
    UIButton *_e28KH6PiWp3;
    UILabel *_dateLabel;
    UIVisualEffectView *_y66kGE1T;
    UILabel *_y3wO3S4ENK;
    UILabel *_g6RhYgLgahDhy;
    LMGaugeView *_d5quAnXZF;
    UIView *_r0tKtCoGv;
    UIView *_u5hLQvkuF;
    NSLayoutConstraint *_x8z6WQVnu8fFNLbsCauUj;
    UINavigationController *_b83bpQWRJ1D0fQAZhG2V4NhRS;
    UINavigationController *_n72ya78t3splyjNfDv;
}

@property(retain, nonatomic) UINavigationController *n72ya78t3splyjNfDv; // @synthesize n72ya78t3splyjNfDv=_n72ya78t3splyjNfDv;
@property(retain, nonatomic) UINavigationController *b83bpQWRJ1D0fQAZhG2V4NhRS; // @synthesize b83bpQWRJ1D0fQAZhG2V4NhRS=_b83bpQWRJ1D0fQAZhG2V4NhRS;
@property(retain, nonatomic) NSLayoutConstraint *x8z6WQVnu8fFNLbsCauUj; // @synthesize x8z6WQVnu8fFNLbsCauUj=_x8z6WQVnu8fFNLbsCauUj;
@property(retain, nonatomic) UIView *u5hLQvkuF; // @synthesize u5hLQvkuF=_u5hLQvkuF;
@property(retain, nonatomic) UIView *r0tKtCoGv; // @synthesize r0tKtCoGv=_r0tKtCoGv;
@property(retain, nonatomic) LMGaugeView *d5quAnXZF; // @synthesize d5quAnXZF=_d5quAnXZF;
@property(retain, nonatomic) UILabel *g6RhYgLgahDhy; // @synthesize g6RhYgLgahDhy=_g6RhYgLgahDhy;
@property(retain, nonatomic) UILabel *y3wO3S4ENK; // @synthesize y3wO3S4ENK=_y3wO3S4ENK;
@property(retain, nonatomic) UIVisualEffectView *y66kGE1T; // @synthesize y66kGE1T=_y66kGE1T;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) UIButton *e28KH6PiWp3; // @synthesize e28KH6PiWp3=_e28KH6PiWp3;
@property(retain, nonatomic) UIButton *v1n37B8BU8u; // @synthesize v1n37B8BU8u=_v1n37B8BU8u;
- (void).cxx_destruct;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)h5ciHaU4jK7;
- (void)q21qHlFKB6Mg:(id)arg1;
- (void)u9qKXg9PUs8KBuaj:(id)arg1;
- (void)initLa7ZfXVR;
- (void)w8gtIw5IklYTGbQJp;
- (void)y2hqWVRBw;
- (void)n7EKRCHYHAAOfm;
- (void)t0d7Z2:(id)arg1;
- (void)p8XznGNhxg:(id)arg1;
- (void)f2UsbNm6tLohPM8;
- (void)g2WPKqFr8OQsZGr9XYtt:(id)arg1;
- (void)b5zEt2RT5:(id)arg1;
- (void)p0MLH5FI:(_Bool)arg1;
- (void)k6VEpyppOP:(id)arg1;
- (void)o2jhjGSXmb:(id)arg1;
- (void)j6yO7yOCCOeSAV;
- (void)timerFired:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)initLz;
- (void)didReceiveMemoryWarning;
- (void)k7QUg4q4NsYU;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;

@end

