//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface o60HgQoJPY : NSObject
{
    int l1yAbXPXs3V;
    double *c8I1cpf4tqSxS;
    int d0VtxJXTbOp0YG;
    int o3hcMbMxyIq6orwb;
    int l5u1eW4Z8Vlgp8;
    struct OpaqueAudioComponentInstance *d7Cuygmw83OoRA;
    int _i3c4ax7;
    _Bool c0PpdmM4;
    double r7MTG;
    double sampleRate;
    _Bool o8H3VLC;
}

@property int i3c4ax7; // @synthesize i3c4ax7=_i3c4ax7;
- (void)stop;
- (_Bool)e1tP7ux:(BOOL)arg1;
- (_Bool)setM3GMImU:(int)arg1 y0fOlai:(const double *)arg2 length:(unsigned int)arg3 o4xJ4YUXHP6T:(_Bool)arg4;
- (_Bool)k5s9sZDfh4PjqXgQ;
- (_Bool)q45mGdE00bs5C;
- (id)init;

@end

