//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface UIButton (j3PMomEMz)
- (id)z9jn56mRjcbRruYbNuTT:(id)arg1;
- (void)c2Iy7u5rUdiuht:(int)arg1 m6spED5iP4n:(_Bool)arg2;
- (void)o64IPzVxks5;
- (void)f9NpEbrKUHc9;
- (void)t4EOda1nm;
- (void)z36smoi6L6Zg;
- (void)j8gAfJdjIdW3;
- (void)i8pieQ2sK6g4;
- (void)a02LZKFYhRevMa;
@end

