//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSNumber, NSString;

@interface x5E4IYvFHTMWn : NSObject
{
    NSNumber *_a8wS9o0U;
    NSString *_n29OBV28;
    NSNumber *_g8U19UpA8;
    NSNumber *_r5U0xaoFSRR;
    NSNumber *_l6zfb3PkVsxiz;
    NSDate *_k6K44HnBAB;
    NSNumber *_e7BxWr5faLoXT3f4;
    NSNumber *_a71JSv7ISvSwv509U;
    NSNumber *_g9LEivpEhCv;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSNumber *g9LEivpEhCv; // @synthesize g9LEivpEhCv=_g9LEivpEhCv;
@property(retain, nonatomic) NSNumber *a71JSv7ISvSwv509U; // @synthesize a71JSv7ISvSwv509U=_a71JSv7ISvSwv509U;
@property(retain, nonatomic) NSNumber *e7BxWr5faLoXT3f4; // @synthesize e7BxWr5faLoXT3f4=_e7BxWr5faLoXT3f4;
@property(retain, nonatomic) NSDate *k6K44HnBAB; // @synthesize k6K44HnBAB=_k6K44HnBAB;
@property(retain, nonatomic) NSNumber *l6zfb3PkVsxiz; // @synthesize l6zfb3PkVsxiz=_l6zfb3PkVsxiz;
@property(retain, nonatomic) NSNumber *r5U0xaoFSRR; // @synthesize r5U0xaoFSRR=_r5U0xaoFSRR;
@property(retain, nonatomic) NSNumber *g8U19UpA8; // @synthesize g8U19UpA8=_g8U19UpA8;
@property(retain, nonatomic) NSString *n29OBV28; // @synthesize n29OBV28=_n29OBV28;
@property(retain, nonatomic) NSNumber *a8wS9o0U; // @synthesize a8wS9o0U=_a8wS9o0U;
- (void).cxx_destruct;
- (void)saveSettings;
- (void)loadSettings;

@end

